[tool.poetry]
name = "curso_aprendizado"
version = "0.1.0"
description = "Use this config file as template for your project."
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.14"
jupyterlab = "^4.3.6"
notebook = "^7.3.3"
pandas = "^2.2.3"
numpy = "^2.2.4"
scikit-learn = "^1.6.1"
matplotlib = "^3.10.1"
seaborn = "^0.13.2"
plotly = "^6.1.2"
spacy = "^3.8.7"
nltk = "^3.9.1"
torch = "^2.7.1"
torchvision = "^0.22.1"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
profile = "black"

[tool.flake8]
max-line-length = 120
max-complexity = 20
exclude = ".git"
select = "B,C,E,F,W,T4,B9"
ignore = "E203, E266, E501, W503, F403, F401"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
black = "^24.3.0"
isort = "^5.13.2"

[tool.poetry.scripts]
post-update = "sh -c 'poetry update && pre-commit install'"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
